export const workshopList = [
    {
        title: "Curso de Maquillaje Natural para Todos los Días",
        titlePage: "Curso de Maquillaje Natural en Barcelona",
        subtitle: "Aprende a realzar tu belleza natural con técnicas sencillas",
        description: "Este curso está diseñado para enseñar las bases del maquillaje natural, ideal para personas que desean un look fresco y luminoso para el día a día.",
        longDescription: "Aprende las mejores técnicas para conseguir un maquillaje natural y radiante, utilizando productos que realzan la belleza sin sobrecargar el rostro. Desde la base perfecta hasta un toque de color, este taller es ideal para quienes buscan una rutina de maquillaje sencilla y efectiva.",
        whatYouWillLearn: [
            "Técnicas para una piel radiante y saludable.",
            "Cómo aplicar una base ligera y duradera.",
            "Sombra de ojos suave y natural.",
            "Maquillaje de cejas sutil para un acabado limpio.",
            "Labios naturales y frescos con texturas ligeras."
        ],
        forWhom: "Este curso está pensado para cualquier persona que quiera aprender a maquillarse de manera natural y sencilla, sin complicaciones.",
        durationPrice: ["4 horas - 150€"],
        location: "Barcelona",
        targetAudience: "Principiantes, personas que buscan un look natural y profesionales del maquillaje básico.",
        imageSrc: "/images/homepage/courses/curso-de-maquillaje.webp",
        link: "/curso-maquillaje-natural-barcelona",
        date: "15 de febrero de 2025",
    },
    {
        title: "Curso de Maquillaje Natural para Profesionales",
        titlePage: "Curso de Maquillaje Natural Profesional en Barcelona",
        subtitle: "Perfecciona tu técnica de maquillaje natural para clientes",
        description: "Este curso está enfocado a maquilladores que desean perfeccionar sus técnicas de maquillaje natural para clientes, ya sea para sesiones fotográficas, novias o cualquier ocasión especial.",
        longDescription: "En este curso aprenderás a crear looks naturales que se adapten a las necesidades de tus clientes, utilizando técnicas profesionales y productos que aseguran un acabado impecable. Ideal para quienes quieren ofrecer un maquillaje más fresco y juvenil a sus clientes.",
        whatYouWillLearn: [
            "Cómo crear una base perfecta y natural para diferentes tipos de piel.",
            "Técnicas de contorno suave para resaltar los rasgos.",
            "Sombra de ojos nude y técnicas de eyeliner natural.",
            "Maquillaje para novias con un look fresco y luminoso.",
            "Maquillaje para sesiones fotográficas con acabado natural."
        ],
        forWhom: "Este curso está dirigido a maquilladores profesionales que buscan ofrecer un maquillaje natural y sofisticado a sus clientes.",
        durationPrice: ["6 horas - 250€"],
        location: "Barcelona",
        targetAudience: "Maquilladores profesionales, personas que desean trabajar en el ámbito del maquillaje natural.",
        imageSrc: "/images/homepage/courses/curso-de-maquillaje.webp",
        link: "/curso-maquillaje-natural-profesional-barcelona",
        date: "28 de febrero de 2025",
    },
    {
        title: "Taller de Maquillaje para el Día a Día",
        titlePage: "Taller de Maquillaje para el Día a Día en Barcelona",
        subtitle: "Crea looks frescos y naturales para cualquier ocasión",
        description: "En este taller aprenderás a crear un maquillaje sencillo y rápido para el día a día. Perfecto para quienes buscan un look natural sin complicaciones.",
        longDescription: "Este taller te enseñará cómo conseguir un maquillaje rápido y fácil, ideal para todas las ocasiones cotidianas. Aprenderás cómo utilizar pocos productos para lograr un look limpio y luminoso que resalte tu belleza natural.",
        whatYouWillLearn: [
            "Aplicación de base ligera y rápida para todos los días.",
            "Técnicas de corrección y concealing sencillas.",
            "Maquillaje de ojos natural con productos multifuncionales.",
            "Maquillaje de labios sutil para un acabado fresco.",
            "Consejos de cómo mantener el maquillaje intacto todo el día."
        ],
        forWhom: "Este taller es perfecto para cualquier persona que quiera aprender a maquillarse de manera rápida y efectiva para el día a día.",
        durationPrice: ["3 horas - 120€"],
        location: "Barcelona",
        targetAudience: "Principiantes y personas que buscan un maquillaje sencillo para su rutina diaria.",
        imageSrc: "/images/homepage/courses/curso-de-maquillaje.webp",
        link: "/taller-maquillaje-dia-a-dia-barcelona",
        date: "10 de marzo de 2025",
    },
    {
        title: "Curso de Maquillaje Natural para Novias",
        titlePage: "Curso de Maquillaje Natural para Novias en Barcelona",
        subtitle: "Realza la belleza de las novias con un look natural y elegante",
        description: "En este curso aprenderás a crear el maquillaje perfecto para novias, con un estilo natural que realza su belleza sin recargar el rostro.",
        longDescription: "Este curso está diseñado para aquellos que desean aprender a maquillar a novias con un estilo fresco, natural y elegante. Te enseñaremos técnicas para lograr un look que dure todo el día sin perder su luminosidad ni frescura.",
        whatYouWillLearn: [
            "Técnicas para una base de maquillaje duradera y luminosa.",
            "Maquillaje de ojos suave y sofisticado para novias.",
            "Cómo resaltar los rasgos con productos naturales.",
            "Consejos para un acabado perfecto que resista todo el día.",
            "Maquillaje para diferentes tipos de piel y preferencias."
        ],
        forWhom: "Ideal para maquilladores profesionales que quieren especializarse en maquillaje para novias, o novias que quieren aprender a hacerlo ellas mismas.",
        durationPrice: ["6 horas - 250€"],
        location: "Barcelona",
        targetAudience: "Maquilladores, novias y futuras artistas del maquillaje para bodas.",
        imageSrc: "/images/homepage/courses/curso-de-maquillaje.webp",
        link: "/curso-maquillaje-natural-novias-barcelona",
        date: "22 de abril de 2025",
    },
    {
        title: "Taller de Maquillaje Natural de Noche",
        titlePage: "Taller de Maquillaje Natural de Noche en Barcelona",
        subtitle: "Transforma tu look diurno en un maquillaje nocturno natural",
        description: "Este taller está diseñado para enseñar cómo transformar un maquillaje de día en un look más sofisticado y elegante para la noche, sin perder la naturalidad.",
        longDescription: "Aprende a crear un maquillaje de noche con un toque natural, ideal para eventos especiales donde no quieres perder la frescura. Te enseñaremos cómo intensificar tu maquillaje de día para la noche, manteniendo un estilo natural.",
        whatYouWillLearn: [
            "Cómo reforzar el maquillaje de día para ocasiones nocturnas.",
            "Técnicas de maquillaje de ojos con acabados suaves pero intensos.",
            "Aplicación de labiales con acabados mate o gloss.",
            "Técnicas para resaltar el rostro sin sobrecargarlo."
        ],
        forWhom: "Este taller es ideal para quienes quieren aprender a adaptar su maquillaje de día a un look de noche sin perder la naturalidad.",
        durationPrice: ["4 horas - 150€"],
        location: "Barcelona",
        targetAudience: "Personas que buscan crear un maquillaje de noche elegante pero natural.",
        imageSrc: "/images/homepage/courses/curso-de-maquillaje.webp",
        link: "/taller-maquillaje-natural-noche-barcelona",
        date: "8 de mayo de 2025",
    }
];
